meta_product_name: "RetsuQ"
meta_title: "RetsuQ"
meta_description: "Let's queue without wasting time."
meta_image: "meta-image.png" # should exist in `app/assets/images/`
meta_url: "Let's queue without wasting time."
